# Generated by Django 4.2 on 2023-12-27 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('ip_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('ip_region', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_city', models.CharField(blank=True, max_length=255, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('pc', 'PC'), ('mobile', 'MOBILE'), ('tablet', 'TABLET'), ('bot', 'BOT')], default='UNKNOWN', max_length=10)),
                ('device', models.CharField(blank=True, max_length=30, null=True)),
                ('browser', models.CharField(blank=True, max_length=30, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=30, null=True)),
                ('system', models.CharField(blank=True, max_length=30, null=True)),
                ('system_version', models.CharField(blank=True, max_length=30, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
