# Generated by Django 4.2 on 2023-12-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='device_type',
            field=models.CharField(choices=[('pc', 'PC'), ('mobile', 'MOBILE'), ('tablet', 'TABLET'), ('bot', 'BOT'), ('unknown', 'UNKNOWN')], default='UNKNOWN', max_length=10),
        ),
    ]
