# Generated by Django 4.2 on 2023-12-27 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Old_No', models.CharField(blank=True, max_length=10, null=True, verbose_name='Old Num.')),
                ('New_No', models.CharField(blank=True, max_length=10, null=True, verbose_name='New Num.')),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pin-Code')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Employee Num')),
                ('Company', models.CharField(blank=True, default='SightSpectrum', max_length=50, null=True)),
                ('Current_Status', models.CharField(choices=[('1', 'Active'), ('2', 'on maternity leave'), ('3', 'on notice period'), ('4', 'Terminated'), ('5', 'on medical leave')], default='1', max_length=50)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='select', max_length=50)),
                ('Date_Of_Birth', models.DateField(blank=True, null=True)),
                ('Date_Of_Joining', models.DateField(blank=True, null=True)),
                ('Training_Period_CTC', models.IntegerField(blank=True, null=True)),
                ('Annual_CTC', models.IntegerField(blank=True, null=True, verbose_name='Annual Salary')),
                ('Employment_Type', models.CharField(choices=[('R', 'Regular'), ('C', 'Contract'), ('E', 'Permenent')], max_length=50)),
                ('physically_challenged', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employement_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hyper_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_detail', to='hrms.employee', verbose_name='Project Lead')),
            ],
        ),
        migrations.CreateModel(
            name='time_sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_hour', models.CharField(blank=True, max_length=250, null=True)),
                ('second_hour', models.CharField(blank=True, max_length=250, null=True)),
                ('third_hour', models.CharField(blank=True, max_length=250, null=True)),
                ('fourth_hour', models.CharField(blank=True, max_length=250, null=True)),
                ('fifth_hour', models.CharField(blank=True, max_length=250, null=True)),
                ('sixth_hour', models.CharField(blank=True, max_length=250, null=True)),
                ('seventh_hour', models.CharField(blank=True, max_length=250, null=True)),
                ('eighth_hour', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technology', models.CharField(max_length=50)),
                ('proficiency', models.IntegerField()),
                ('hyperlinked_fields', models.ManyToManyField(to='hrms.hyper_fields')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
        ),
        migrations.CreateModel(
            name='team_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='hrms.employee')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_name', to='hrms.project')),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_promotion', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_scale', models.CharField(blank=True, max_length=255, null=True)),
                ('nature_promotion', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Promotions', to='hrms.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Previous_Work_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('reason_for_leaving', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_as_per_Aadhar', models.CharField(blank=True, max_length=50, null=True)),
                ('Father_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Spouse_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Mother_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Aadhar_Card_No', models.BigIntegerField(blank=True, null=True)),
                ('Passport_Number', models.BigIntegerField(blank=True, null=True)),
                ('Passport_issue_date', models.DateField(blank=True, null=True)),
                ('Password_Valid_upto', models.DateField(blank=True, max_length=200, null=True)),
                ('Password_place_of_issue', models.CharField(blank=True, max_length=150, null=True)),
                ('Marital_Status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=50)),
                ('Blood_Group', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('Alternate_Mobile_Number', models.CharField(blank=True, max_length=50, null=True)),
                ('Personal_Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Prefered_contact_Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Company_Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Permanent_Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_add', to='hrms.address_model')),
                ('present_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_add', to='hrms.address_model')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal_detail',
                'verbose_name_plural': 'Personal_detail',
            },
        ),
        migrations.CreateModel(
            name='monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.attendance')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
                ('leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.leave')),
                ('timesheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.time_sheet')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('read', models.BooleanField(default=False)),
                ('write', models.BooleanField(default=False)),
                ('speak', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='hrms.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Joining_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('document_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('procured_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Educational_Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=50)),
                ('specialization', models.CharField(blank=True, max_length=50, null=True)),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('Year_Of_Passing', models.CharField(max_length=50)),
                ('Precentage', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.personal_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Deparment_and_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deparment', models.CharField(blank=True, max_length=50, null=True)),
                ('Designation', models.CharField(blank=True, max_length=50, null=True)),
                ('Reports_to', models.CharField(blank=True, max_length=50, null=True)),
                ('Grade', models.CharField(blank=True, max_length=50, null=True)),
                ('Branch', models.CharField(blank=True, max_length=50, null=True)),
                ('Salary_Mode', models.CharField(blank=True, max_length=50, null=True)),
                ('Payroll_Cost_Center', models.CharField(blank=True, max_length=50, null=True)),
                ('PAN_Number', models.CharField(blank=True, max_length=50, null=True)),
                ('Provident_Fund_Account', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
            options={
                'verbose_name': 'Deparment_and_Grade',
                'verbose_name_plural': 'Deparment_and_Grade',
            },
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='SightSpectrum', max_length=50)),
                ('resource_type', models.CharField(choices=[('E', 'EXTERNEL'), ('I', 'INTERNEL'), ('U', 'UNDER TRAINING')], default='U', max_length=50)),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_name', to='hrms.project')),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('otherother', 'other')], max_length=32)),
                ('dob', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Children', to='hrms.personal_detail')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee'),
        ),
    ]
