# Generated by Django 4.2 on 2023-12-29 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Emp_id',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='joining_details',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.personal_detail'),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
